# Generated by Django 4.2.20 on 2025-05-08 04:13

import django.core.serializers.json
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import nautobot.core.models.fields
import nautobot.extras.models.mixins
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('extras', '0122_add_graphqlquery_owner_content_type'),
        ('nautobot_dns_models', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DNSRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('_custom_field_data', models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('enabled', models.BooleanField(default=True)),
                ('priority', models.PositiveIntegerField(default=1000)),
                ('zone_template', models.TextField()),
                ('record_type', models.CharField(max_length=10)),
                ('name_template', models.TextField()),
                ('value_template', models.TextField()),
                ('ttl', models.IntegerField(default=3600, validators=[django.core.validators.MinValueValidator(300), django.core.validators.MaxValueValidator(2147483647)])),
                ('mx_preference', models.IntegerField(blank=True, default=10, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(65535)])),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('tags', nautobot.core.models.fields.TagsField(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'verbose_name': 'DNS Rule',
                'verbose_name_plural': 'DNS Rules',
                'ordering': ('name', 'priority'),
            },
            bases=(nautobot.extras.models.mixins.DynamicGroupMixin, nautobot.extras.models.mixins.NotesMixin, models.Model),
        ),
        migrations.AddConstraint(
            model_name='dnsrule',
            constraint=models.UniqueConstraint(fields=('content_type', 'record_type'), name='unique_content_type_record_type'),
        ),
    ]
