# Generated by Django 4.2.23 on 2025-08-12 23:56

import uuid

import django.core.serializers.json
import django.db.models.deletion
import nautobot.core.models.fields
import nautobot.extras.models.mixins
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("extras", "0122_add_graphqlquery_owner_content_type"),
        ("nautobot_dns_models", "0003_remove_aaaarecordmodel_ttl_remove_arecordmodel_ttl_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DNSRule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True, null=True)),
                (
                    "_custom_field_data",
                    models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
                ("enabled", models.BooleanField(default=True)),
                ("priority", models.IntegerField(default=100)),
                ("zone_template", models.TextField()),
                ("record_type", models.CharField(max_length=10)),
                ("name_template", models.TextField()),
                ("value_template", models.TextField(blank=True)),
                ("preference_template", models.TextField(blank=True)),
                ("priority_template", models.TextField(blank=True)),
                ("weight_template", models.TextField(blank=True)),
                ("port_template", models.TextField(blank=True)),
                (
                    "content_type",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="contenttypes.contenttype"),
                ),
                ("tags", nautobot.core.models.fields.TagsField(through="extras.TaggedItem", to="extras.Tag")),
            ],
            options={
                "verbose_name": "DNS Rule",
                "verbose_name_plural": "DNS Rules",
                "ordering": ["priority", "name"],
            },
            bases=(
                nautobot.extras.models.mixins.DynamicGroupMixin,
                nautobot.extras.models.mixins.NotesMixin,
                models.Model,
            ),
        ),
        migrations.CreateModel(
            name="DNSRuleRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("object_id", models.PositiveIntegerField()),
                ("dns_record_object_id", models.PositiveIntegerField()),
                (
                    "content_type",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="contenttypes.contenttype"),
                ),
                (
                    "dns_record_content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rule_records",
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "rule",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="nautobot_dns_models.dnsrule"),
                ),
            ],
            options={
                "verbose_name": "DNS Rule Record",
                "verbose_name_plural": "DNS Rule Records",
                "unique_together": {
                    ("rule", "content_type", "object_id", "dns_record_content_type", "dns_record_object_id")
                },
            },
        ),
    ]
