# Generated by Django 4.2.23 on 2025-08-13 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nautobot_dns_models', '0004_dnsrule_dnsrulerecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dnsrulerecord',
            name='dns_record_object_id',
            field=models.CharField(max_length=36),
        ),
        migrations.AlterField(
            model_name='dnsrulerecord',
            name='object_id',
            field=models.CharField(max_length=36),
        ),
    ]
