# Generated by Django 4.2.23 on 2025-09-27 04:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dcim", "0073_alter_powerport_power_factor_and_more"),
        ("nautobot_dns_models", "0005_dnsrule_dnsrulerecord"),
    ]

    operations = [
        migrations.AddField(
            model_name="dnsrule",
            name="location",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to="dcim.location"
            ),
        ),
        migrations.AddConstraint(
            model_name="dnsrule",
            constraint=models.UniqueConstraint(
                fields=("content_type", "record_type", "location"), name="unique_rule_per_content_record_location"
            ),
        ),
    ]
