# Generated by Django 4.2.25 on 2025-11-08 02:09

import uuid

import django.core.serializers.json
import django.db.models.deletion
import nautobot.core.models.fields
import nautobot.extras.models.mixins
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("extras", "0125_jobresult_date_started"),
        ("dcim", "0074_alter_rack_u_height"),
        ("contenttypes", "0002_remove_content_type_name"),
        ("tenancy", "0009_update_all_charfields_max_length_to_255"),
        ("nautobot_dns_models", "0005_dnsview_alter_dnszone_name_dnsviewprefixassignment_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DNSRule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True, null=True)),
                (
                    "_custom_field_data",
                    models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.CharField(blank=True, max_length=255)),
                ("enabled", models.BooleanField(default=True)),
                ("zone_template", models.TextField()),
                ("record_type", models.CharField(max_length=10)),
                ("name_template", models.TextField()),
                ("value_template", models.TextField()),
                (
                    "content_type",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="contenttypes.contenttype"),
                ),
                (
                    "location",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to="dcim.location"
                    ),
                ),
                ("tags", nautobot.core.models.fields.TagsField(through="extras.TaggedItem", to="extras.Tag")),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to="tenancy.tenant"
                    ),
                ),
            ],
            options={
                "verbose_name": "DNS Rule",
                "ordering": ["name"],
            },
            bases=(
                nautobot.extras.models.mixins.DynamicGroupMixin,
                nautobot.extras.models.mixins.NotesMixin,
                models.Model,
            ),
        ),
        migrations.CreateModel(
            name="DNSRuleRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("object_id", models.UUIDField(db_index=True)),
                ("dns_record_object_id", models.UUIDField(db_index=True)),
                (
                    "content_type",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="contenttypes.contenttype"),
                ),
                (
                    "dns_record_content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rule_records",
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "rule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rule_records",
                        to="nautobot_dns_models.dnsrule",
                    ),
                ),
            ],
            options={
                "verbose_name": "DNS Rule Record",
                "verbose_name_plural": "DNS Rule Records",
                "unique_together": {("content_type", "object_id", "dns_record_content_type", "dns_record_object_id")},
            },
        ),
        migrations.AddConstraint(
            model_name="dnsrule",
            constraint=models.UniqueConstraint(
                condition=models.Q(("enabled", True)),
                fields=("content_type", "record_type", "location", "tenant"),
                name="unique_enabled_rule_per_content_record_location_tenant",
            ),
        ),
    ]
