# Generated by Django 4.2.28 on 2026-04-28 18:36

import uuid

import django.core.serializers.json
import django.db.models.deletion
import nautobot.core.models.fields
import nautobot.extras.models.mixins
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dcim", "0075_interface_duplex_interface_speed_and_more"),
        ("extras", "0125_jobresult_date_started"),
        ("tenancy", "0009_update_all_charfields_max_length_to_255"),
        ("contenttypes", "0002_remove_content_type_name"),
        ("nautobot_dns_models", "0005_dnsview_alter_dnszone_name_dnsviewprefixassignment_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DNSRule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True, null=True)),
                (
                    "_custom_field_data",
                    models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.CharField(blank=True, max_length=255)),
                ("enabled", models.BooleanField(default=True)),
                ("view_template", models.TextField(blank=True)),
                ("zone_template", models.TextField()),
                ("record_type", models.CharField(max_length=10)),
                ("name_template", models.TextField()),
                ("value_template", models.TextField()),
                (
                    "content_type",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="contenttypes.contenttype"),
                ),
                (
                    "location",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to="dcim.location"
                    ),
                ),
                ("tags", nautobot.core.models.fields.TagsField(through="extras.TaggedItem", to="extras.Tag")),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to="tenancy.tenant"
                    ),
                ),
            ],
            options={
                "verbose_name": "DNS Rule",
                "ordering": ["name"],
            },
            bases=(
                nautobot.extras.models.mixins.DynamicGroupMixin,
                nautobot.extras.models.mixins.NotesMixin,
                models.Model,
            ),
        ),
        migrations.CreateModel(
            name="DNSRuleRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("object_id", models.UUIDField(db_index=True)),
                ("dns_record_object_id", models.UUIDField(db_index=True)),
                (
                    "content_type",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="contenttypes.contenttype"),
                ),
                (
                    "dns_record_content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rule_records",
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "rule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rule_records",
                        to="nautobot_dns_models.dnsrule",
                    ),
                ),
            ],
            options={
                "verbose_name": "DNS Rule Record",
                "verbose_name_plural": "DNS Rule Records",
                "unique_together": {("dns_record_content_type", "dns_record_object_id")},
            },
        ),
        migrations.CreateModel(
            name="DNSRuleFailureState",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("source_object_id", models.UUIDField(db_index=True)),
                ("candidate_record_type", models.CharField(max_length=16)),
                ("candidate_name", models.CharField(max_length=255)),
                ("candidate_zone_id", models.UUIDField(blank=True, db_index=True, null=True)),
                ("candidate_address_id", models.UUIDField(blank=True, db_index=True, null=True)),
                ("latest_exception_type", models.CharField(blank=True, default="", max_length=128)),
                ("latest_error", models.TextField(blank=True, default="")),
                ("latest_pgcode", models.CharField(blank=True, default="", max_length=32)),
                ("latest_constraint", models.CharField(blank=True, default="", max_length=255)),
                ("first_seen", models.DateTimeField()),
                ("last_seen", models.DateTimeField()),
                ("attempt_count", models.PositiveIntegerField(default=1)),
                ("consecutive_failures", models.PositiveIntegerField(default=1)),
                (
                    "rule",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="failure_states",
                        to="nautobot_dns_models.dnsrule",
                    ),
                ),
                (
                    "source_content_type",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="contenttypes.contenttype"),
                ),
            ],
            options={
                "verbose_name": "DNS Rule Failure State",
                "verbose_name_plural": "DNS Rule Failure States",
                "indexes": [
                    models.Index(fields=["source_content_type", "source_object_id"], name="dnsrulefail_src_idx"),
                    models.Index(
                        fields=["candidate_record_type", "candidate_zone_id", "candidate_name"],
                        name="dnsrulefail_candidate_idx",
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="dnsrulefailurestate",
            constraint=models.UniqueConstraint(
                fields=(
                    "source_content_type",
                    "source_object_id",
                    "rule",
                    "candidate_record_type",
                    "candidate_name",
                    "candidate_zone_id",
                    "candidate_address_id",
                ),
                name="dnsrulefail_unique_state_key",
            ),
        ),
    ]
