# Generated by Django 4.2.23 on 2025-09-27 07:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("nautobot_dns_models", "0006_add_location_field_to_dnsrule"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="dnsrule",
            name="unique_rule_per_content_record_location",
        ),
        migrations.AddConstraint(
            model_name="dnsrule",
            constraint=models.UniqueConstraint(
                condition=models.Q(("enabled", True)),
                fields=("content_type", "record_type", "location"),
                name="unique_enabled_rule_per_content_record_location",
            ),
        ),
    ]
