# Generated by Django 4.2.23 on 2025-08-13 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nautobot_dns_models', '0006_alter_dnsrule_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dnsrulerecord',
            name='dns_record_object_id',
            field=models.UUIDField(db_index=True),
        ),
        migrations.AlterField(
            model_name='dnsrulerecord',
            name='object_id',
            field=models.UUIDField(db_index=True),
        ),
    ]
