# Generated by Django 5.2.14 on 2026-05-14 20:12

import uuid

import django.db.models.deletion
import nautobot.core.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("nautobot_dns_models", "0007_dnsregistrar_dnsregistration"),
    ]

    operations = [
        migrations.CreateModel(
            name="CatalogZone",
            fields=[],
            options={
                "verbose_name": "Catalog Zone",
                "verbose_name_plural": "Catalog Zones",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("nautobot_dns_models.dnszone",),
        ),
        migrations.AddField(
            model_name="dnszone",
            name="is_catalog_zone",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="CatalogZoneMembership",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True
                    ),
                ),
                (
                    "member_zone",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="membership",
                        to="nautobot_dns_models.dnszone",
                    ),
                ),
                (
                    "catalog_zone",
                    nautobot.core.models.fields.ForeignKeyWithAutoRelatedName(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="memberships",
                        to="nautobot_dns_models.catalogzone",
                    ),
                ),
            ],
            options={
                "verbose_name": "Catalog Zone Membership",
                "verbose_name_plural": "Catalog Zone Memberships",
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("catalog_zone", models.F("member_zone")), _negated=True),
                        name="nautobot_dns_models_catalogzonemembership_not_self",
                    )
                ],
            },
        ),
    ]
