# Generated by Django 4.2.23 on 2025-08-13 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nautobot_dns_models', '0007_alter_dnsrulerecord_dns_record_object_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dnsrule',
            name='value_template',
            field=models.TextField(),
        ),
    ]
