# Generated by Django 4.2.28 on 2026-05-11 19:28

import uuid

import django.core.serializers.json
import django.core.validators
import django.db.models.deletion
import nautobot.core.models.fields
import nautobot.extras.models.mixins
from django.db import migrations, models

import nautobot_dns_models.models


class Migration(migrations.Migration):
    dependencies = [
        ("extras", "0133_alter_approvalworkflowstageresponse_options_and_more"),
        ("nautobot_dns_models", "0007_dnsregistrar_dnsregistration"),
    ]

    operations = [
        migrations.CreateModel(
            name="CatalogZone",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True, null=True)),
                (
                    "_custom_field_data",
                    models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "ttl",
                    models.IntegerField(
                        default=3600,
                        validators=[
                            django.core.validators.MinValueValidator(300),
                            django.core.validators.MaxValueValidator(2147483647),
                        ],
                    ),
                ),
                ("filename", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("soa_mname", models.CharField(max_length=200)),
                ("soa_rname", models.EmailField(max_length=254)),
                (
                    "soa_refresh",
                    models.IntegerField(
                        default=86400,
                        validators=[
                            django.core.validators.MinValueValidator(300),
                            django.core.validators.MaxValueValidator(2147483647),
                        ],
                    ),
                ),
                (
                    "soa_retry",
                    models.IntegerField(
                        default=7200,
                        validators=[
                            django.core.validators.MinValueValidator(300),
                            django.core.validators.MaxValueValidator(2147483647),
                        ],
                    ),
                ),
                (
                    "soa_expire",
                    models.IntegerField(
                        default=3600000,
                        validators=[
                            django.core.validators.MinValueValidator(300),
                            django.core.validators.MaxValueValidator(2147483647),
                        ],
                    ),
                ),
                (
                    "soa_serial",
                    models.IntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(2147483647),
                        ],
                    ),
                ),
                (
                    "soa_minimum",
                    models.IntegerField(
                        default=3600,
                        validators=[
                            django.core.validators.MinValueValidator(300),
                            django.core.validators.MaxValueValidator(2147483647),
                        ],
                    ),
                ),
                ("schema_version", models.CharField(default="2", max_length=8)),
                (
                    "dns_view",
                    nautobot.core.models.fields.ForeignKeyWithAutoRelatedName(
                        default=nautobot_dns_models.models.get_default_view_pk,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="nautobot_dns_models.dnsview",
                    ),
                ),
            ],
            options={
                "verbose_name": "Catalog Zone",
                "verbose_name_plural": "Catalog Zones",
            },
            bases=(
                nautobot.extras.models.mixins.DataComplianceModelMixin,
                nautobot.extras.models.mixins.DynamicGroupMixin,
                nautobot.extras.models.mixins.NotesMixin,
                models.Model,
            ),
        ),
        migrations.CreateModel(
            name="CatalogZoneMembership",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("member_node_label", models.CharField(blank=True, max_length=63, null=True)),
                (
                    "catalog_zone",
                    nautobot.core.models.fields.ForeignKeyWithAutoRelatedName(
                        on_delete=django.db.models.deletion.CASCADE, to="nautobot_dns_models.catalogzone"
                    ),
                ),
                (
                    "member_zone",
                    nautobot.core.models.fields.ForeignKeyWithAutoRelatedName(
                        on_delete=django.db.models.deletion.PROTECT, to="nautobot_dns_models.dnszone"
                    ),
                ),
            ],
            options={
                "verbose_name": "Catalog Zone Membership",
                "verbose_name_plural": "Catalog Zone Memberships",
                "unique_together": {("catalog_zone", "member_zone"), ("catalog_zone", "member_node_label")},
            },
        ),
        migrations.AddField(
            model_name="catalogzone",
            name="members",
            field=models.ManyToManyField(
                blank=True,
                related_name="catalog_zones",
                through="nautobot_dns_models.CatalogZoneMembership",
                to="nautobot_dns_models.dnszone",
            ),
        ),
        migrations.AddField(
            model_name="catalogzone",
            name="tags",
            field=nautobot.core.models.fields.TagsField(through="extras.TaggedItem", to="extras.Tag"),
        ),
        migrations.AlterUniqueTogether(
            name="catalogzone",
            unique_together={("name", "dns_view")},
        ),
    ]
