# Generated by Django 4.2.28 on 2026-05-12 06:05

import uuid

import django.core.serializers.json
import django.db.models.deletion
import nautobot.core.models.fields
import nautobot.extras.models.mixins
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("extras", "0133_alter_approvalworkflowstageresponse_options_and_more"),
        ("nautobot_dns_models", "0007_dnsregistrar_dnsregistration"),
    ]

    operations = [
        migrations.CreateModel(
            name="CatalogZone",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True, null=True)),
                (
                    "_custom_field_data",
                    models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder),
                ),
                (
                    "dns_zone",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="catalog_zone",
                        to="nautobot_dns_models.dnszone",
                    ),
                ),
            ],
            options={
                "verbose_name": "Catalog Zone",
                "verbose_name_plural": "Catalog Zones",
            },
            bases=(
                nautobot.extras.models.mixins.DataComplianceModelMixin,
                nautobot.extras.models.mixins.DynamicGroupMixin,
                nautobot.extras.models.mixins.NotesMixin,
                models.Model,
            ),
        ),
        migrations.CreateModel(
            name="CatalogZoneMembership",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True, null=True)),
                (
                    "_custom_field_data",
                    models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder),
                ),
                ("member_node_label", models.CharField(blank=True, max_length=63)),
                (
                    "catalog_zone",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="memberships",
                        to="nautobot_dns_models.catalogzone",
                    ),
                ),
                (
                    "member_zone",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="catalog_zone_memberships",
                        to="nautobot_dns_models.dnszone",
                    ),
                ),
                ("tags", nautobot.core.models.fields.TagsField(through="extras.TaggedItem", to="extras.Tag")),
            ],
            options={
                "verbose_name": "Catalog Zone Membership",
                "verbose_name_plural": "Catalog Zone Memberships",
            },
            bases=(
                nautobot.extras.models.mixins.DataComplianceModelMixin,
                nautobot.extras.models.mixins.DynamicGroupMixin,
                nautobot.extras.models.mixins.NotesMixin,
                models.Model,
            ),
        ),
        migrations.AddField(
            model_name="catalogzone",
            name="members",
            field=models.ManyToManyField(
                blank=True,
                related_name="member_of_catalog_zones",
                through="nautobot_dns_models.CatalogZoneMembership",
                to="nautobot_dns_models.dnszone",
            ),
        ),
        migrations.AddField(
            model_name="catalogzone",
            name="tags",
            field=nautobot.core.models.fields.TagsField(through="extras.TaggedItem", to="extras.Tag"),
        ),
        migrations.AddConstraint(
            model_name="catalogzonemembership",
            constraint=models.UniqueConstraint(
                fields=("catalog_zone", "member_zone"), name="dns_czm_unique_member_zone_per_catalog"
            ),
        ),
        migrations.AddConstraint(
            model_name="catalogzonemembership",
            constraint=models.UniqueConstraint(
                fields=("catalog_zone", "member_node_label"), name="dns_czm_unique_member_node_label_per_catalog"
            ),
        ),
    ]
