# Generated by Django 4.2.24 on 2025-09-27 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nautobot_dns_models', '0008_alter_dnsrule_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dnsrule',
            options={'ordering': ['name']},
        ),
        migrations.RemoveField(
            model_name='dnsrule',
            name='priority',
        ),
    ]
