# Generated by Django 5.2.16 on 2026-08-03 03:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("nautobot_dns_models", "0009_alter_aaaarecord__ttl_alter_arecord__ttl_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="dnszone",
            name="zone_type",
            field=models.CharField(default="primary", max_length=50),
        ),
        migrations.AddConstraint(
            model_name="dnszone",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("zone_type", "catalog"), _negated=True), ("auto_create_ptr", False), _connector="OR"
                ),
                name="catalog_zone_no_auto_create_ptr",
                violation_error_code="catalog_zone_auto_create_ptr",
                violation_error_message="Catalog zones cannot enable automatic PTR creation.",
            ),
        ),
    ]
