# Generated by Django 4.2.24 on 2025-09-28 01:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenancy", "0009_update_all_charfields_max_length_to_255"),
        ("nautobot_dns_models", "0009_alter_dnsrule_options_remove_dnsrule_priority"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="dnsrule",
            options={"ordering": ["name"], "verbose_name": "DNS Rule"},
        ),
        migrations.RemoveConstraint(
            model_name="dnsrule",
            name="unique_enabled_rule_per_content_record_location",
        ),
        migrations.AddField(
            model_name="dnsrule",
            name="tenant",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to="tenancy.tenant"
            ),
        ),
        migrations.AddConstraint(
            model_name="dnsrule",
            constraint=models.UniqueConstraint(
                condition=models.Q(("enabled", True)),
                fields=("content_type", "record_type", "location", "tenant"),
                name="unique_enabled_rule_per_content_record_location_tenant",
            ),
        ),
    ]
