# Generated by Django 5.2.17 on 2026-08-13 17:42

import uuid

import django.db.models.deletion
import nautobot.core.models.fields
from django.db import migrations, models

import nautobot_dns_models.models


class Migration(migrations.Migration):
    dependencies = [
        ("extras", "0145_objectmetadata_assigned_object_type_cascade"),
        ("nautobot_dns_models", "0010_aaaarecord_enabled_arecord_enabled_and_more"),
        ("tenancy", "0009_update_all_charfields_max_length_to_255"),
    ]

    operations = [
        migrations.AddField(
            model_name="dnszone",
            name="zone_type",
            field=models.CharField(default="primary", max_length=50),
        ),
        migrations.CreateModel(
            name="CatalogZoneMember",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True
                    ),
                ),
                (
                    "member_label",
                    models.CharField(
                        blank=True, default=nautobot_dns_models.models.catalog_member_label, max_length=63
                    ),
                ),
                (
                    "catalog_zone",
                    nautobot.core.models.fields.ForeignKeyWithAutoRelatedName(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="catalog_memberships",
                        to="nautobot_dns_models.dnszone",
                    ),
                ),
                (
                    "member_zone",
                    nautobot.core.models.fields.ForeignKeyWithAutoRelatedName(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="catalog_membership",
                        to="nautobot_dns_models.dnszone",
                    ),
                ),
            ],
            options={
                "verbose_name": "Catalog Zone Member",
                "verbose_name_plural": "Catalog Zone Members",
                "ordering": ["catalog_zone", "member_label"],
            },
        ),
        migrations.AddField(
            model_name="dnszone",
            name="catalogs",
            field=models.ManyToManyField(
                blank=True,
                related_name="members",
                through="nautobot_dns_models.CatalogZoneMember",
                through_fields=("member_zone", "catalog_zone"),
                to="nautobot_dns_models.dnszone",
            ),
        ),
        migrations.AddConstraint(
            model_name="dnszone",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("zone_type", "catalog"), _negated=True), ("auto_create_ptr", False), _connector="OR"
                ),
                name="catalog_zone_no_auto_create_ptr",
                violation_error_code="catalog_zone_auto_create_ptr",
                violation_error_message="Catalog zones cannot enable automatic PTR creation.",
            ),
        ),
        migrations.AddConstraint(
            model_name="catalogzonemember",
            constraint=models.UniqueConstraint(
                fields=("member_zone",),
                name="catalog_zone_member_unique_member_zone",
                violation_error_message="This zone already belongs to a catalog zone.",
            ),
        ),
        migrations.AddConstraint(
            model_name="catalogzonemember",
            constraint=models.UniqueConstraint(
                fields=("catalog_zone", "member_label"),
                name="catalog_zone_member_unique_label",
                violation_error_message="This label is already used by another member of the catalog zone.",
            ),
        ),
    ]
