# Generated by Django 4.2.24 on 2025-09-28 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nautobot_dns_models', '0010_alter_dnsrule_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dnsrulerecord',
            name='rule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rule_records', to='nautobot_dns_models.dnsrule'),
        ),
    ]
