# Generated by Django 5.2.16 on 2026-08-04 00:21

import uuid

import django.core.serializers.json
import django.db.models.deletion
import nautobot.core.models.fields
import nautobot.extras.models.mixins
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("nautobot_dns_models", "0010_dnszone_zone_type_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CatalogZoneMember",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True, null=True)),
                (
                    "_custom_field_data",
                    models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder),
                ),
                ("member_label", models.CharField(blank=True, max_length=63)),
                (
                    "catalog_zone",
                    nautobot.core.models.fields.ForeignKeyWithAutoRelatedName(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="catalog_memberships",
                        to="nautobot_dns_models.dnszone",
                    ),
                ),
                (
                    "member_zone",
                    nautobot.core.models.fields.ForeignKeyWithAutoRelatedName(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="catalog_membership",
                        to="nautobot_dns_models.dnszone",
                    ),
                ),
                ("tags", nautobot.core.models.fields.TagsField(through="extras.TaggedItem", to="extras.Tag")),
            ],
            options={
                "verbose_name": "Catalog Zone Member",
                "verbose_name_plural": "Catalog Zone Members",
                "ordering": ["catalog_zone", "member_label"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("member_zone",),
                        name="catalog_zone_member_unique_member_zone",
                        violation_error_message="This zone already belongs to a catalog zone.",
                    ),
                    models.UniqueConstraint(
                        fields=("catalog_zone", "member_label"),
                        name="catalog_zone_member_unique_label",
                        violation_error_message="This label is already used by another member of the catalog zone.",
                    ),
                ],
            },
            bases=(
                nautobot.extras.models.mixins.DataComplianceModelMixin,
                nautobot.extras.models.mixins.DynamicGroupMixin,
                nautobot.extras.models.mixins.NotesMixin,
                models.Model,
            ),
        ),
    ]
