# Generated by Django 4.2.24 on 2025-10-01 01:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("nautobot_dns_models", "0011_alter_dnsrulerecord_rule"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="dnsrulerecord",
            unique_together={("content_type", "object_id", "dns_record_content_type", "dns_record_object_id")},
        ),
    ]
