# Generated by Django 5.2.16 on 2026-08-06 00:56

import uuid

import django.core.serializers.json
import django.db.models.deletion
import nautobot.core.models.fields
import nautobot.extras.models.mixins
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("extras", "0145_objectmetadata_assigned_object_type_cascade"),
        ("nautobot_dns_models", "0011_dnszone_enabled"),
        ("tenancy", "0009_update_all_charfields_max_length_to_255"),
    ]

    operations = [
        migrations.CreateModel(
            name="CatalogZoneMember",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True, null=True)),
                (
                    "_custom_field_data",
                    models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder),
                ),
                ("member_label", models.CharField(blank=True, max_length=63)),
            ],
            options={
                "verbose_name": "Catalog Zone Member",
                "verbose_name_plural": "Catalog Zone Members",
                "ordering": ["catalog_zone", "member_label"],
            },
            bases=(
                nautobot.extras.models.mixins.DataComplianceModelMixin,
                nautobot.extras.models.mixins.DynamicGroupMixin,
                nautobot.extras.models.mixins.NotesMixin,
                models.Model,
            ),
        ),
        migrations.AddField(
            model_name="dnszone",
            name="zone_type",
            field=models.CharField(default="primary", max_length=50),
        ),
        migrations.AddConstraint(
            model_name="dnszone",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("zone_type", "catalog"), _negated=True), ("auto_create_ptr", False), _connector="OR"
                ),
                name="catalog_zone_no_auto_create_ptr",
                violation_error_code="catalog_zone_auto_create_ptr",
                violation_error_message="Catalog zones cannot enable automatic PTR creation.",
            ),
        ),
        migrations.AddField(
            model_name="catalogzonemember",
            name="catalog_zone",
            field=nautobot.core.models.fields.ForeignKeyWithAutoRelatedName(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="catalog_memberships",
                to="nautobot_dns_models.dnszone",
            ),
        ),
        migrations.AddField(
            model_name="catalogzonemember",
            name="member_zone",
            field=nautobot.core.models.fields.ForeignKeyWithAutoRelatedName(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="catalog_membership",
                to="nautobot_dns_models.dnszone",
            ),
        ),
        migrations.AddField(
            model_name="catalogzonemember",
            name="tags",
            field=nautobot.core.models.fields.TagsField(through="extras.TaggedItem", to="extras.Tag"),
        ),
        migrations.AddConstraint(
            model_name="catalogzonemember",
            constraint=models.UniqueConstraint(
                fields=("member_zone",),
                name="catalog_zone_member_unique_member_zone",
                violation_error_message="This zone already belongs to a catalog zone.",
            ),
        ),
        migrations.AddConstraint(
            model_name="catalogzonemember",
            constraint=models.UniqueConstraint(
                fields=("catalog_zone", "member_label"),
                name="catalog_zone_member_unique_label",
                violation_error_message="This label is already used by another member of the catalog zone.",
            ),
        ),
    ]
