# Generated by Django 5.2.16 on 2026-08-10 15:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("nautobot_dns_models", "0012_catalog_zones"),
    ]

    operations = [
        migrations.AddField(
            model_name="dnszone",
            name="catalogs",
            field=models.ManyToManyField(
                blank=True,
                related_name="members",
                through="nautobot_dns_models.CatalogZoneMember",
                through_fields=("member_zone", "catalog_zone"),
                to="nautobot_dns_models.dnszone",
            ),
        ),
    ]
