# Generated by Django 5.2.17 on 2026-08-10 15:47

from django.db import migrations, models

import nautobot_dns_models.models


class Migration(migrations.Migration):
    dependencies = [
        ("nautobot_dns_models", "0013_dnszone_catalogs"),
    ]

    operations = [
        migrations.AlterField(
            model_name="catalogzonemember",
            name="member_label",
            field=models.CharField(blank=True, default=nautobot_dns_models.models.catalog_member_label, max_length=63),
        ),
    ]
