# Generated by Django 5.2.17 on 2026-08-10 15:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("nautobot_dns_models", "0014_alter_catalogzonemember_member_label"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="catalogzonemember",
            name="_custom_field_data",
        ),
        migrations.RemoveField(
            model_name="catalogzonemember",
            name="created",
        ),
        migrations.RemoveField(
            model_name="catalogzonemember",
            name="last_updated",
        ),
        migrations.RemoveField(
            model_name="catalogzonemember",
            name="tags",
        ),
    ]
